version: "2"
services: 
  radicale:
    build:
      context: radicale
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5232:5232"
  agendav: 
    build:
      context: agendav
      dockerfile: Dockerfile
    links:
      - agendav-db:postgres
    restart: always
    ports:
      - "8080:80"
  agendav-db: 
    build: 
      context: agendav
      dockerfile: Dockerfile-db
    restart: always
